version: "3.4"
services:
  workoutdb:
    container_name: workoutdb
    image: mysql:5.7
    command: mysqld --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      TZ: America/Sao_Paulo
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_USER: igor
      MYSQL_PASSWORD: 123456
      MYSQL_DATABASE: workoutdb
    ports:
      - "3308:3306"
    volumes:
      - ./docker-data/mysql/data:/var/lib/mysql