definitions:
  request.ExerciseRequest:
    properties:
      muscle_group:
        example: Chest
        type: string
      name:
        example: Bench Press
        type: string
      reps:
        example: 12
        type: integer
      rest:
        example: 60
        type: integer
      weight:
        example: 20
        type: integer
    type: object
  response.ExerciseResponse:
    properties:
      id:
        type: integer
      muscular_group:
        type: string
      name:
        type: string
      reps:
        type: integer
      rest:
        type: integer
      weight:
        type: integer
    type: object
info:
  contact: {}
paths:
  /exercises:
    post:
      consumes:
      - application/json
      parameters:
      - description: Add an exercise
        in: body
        name: food
        required: true
        schema:
          $ref: '#/definitions/request.ExerciseRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/response.ExerciseResponse'
      security:
      - ApiKeyAuth: []
      summary: Create a new exercise
      tags:
      - exercise
  /exercises/{id}:
    get:
      consumes:
      - application/json
      parameters:
      - description: Exercise ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.ExerciseResponse'
      security:
      - ApiKeyAuth: []
      summary: Find exercise by id
      tags:
      - exercise
swagger: "2.0"
