CREATE TABLE IF NOT EXISTS workoutdb.exercises (
    id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(75) NOT NULL,
    muscular_group VARCHAR(75) NOT NULL,
    reps INTEGER NOT NULL,
    rest_time INTEGER NOT NULL
) ENGINE = InnoDB DEFAULT CHARSET = latin1;