CREATE TABLE IF NOT EXISTS workoutdb.exercise (
    id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(75) NOT NULL,
    muscular_group VARCHAR(75) NOT NULL,
    reps INTEGER NOT NULL,
    weight INTEGER NOT NULL
) ENGINE = InnoDB DEFAULT CHARSET = latin1;